# OUTNAME = self_update-$(BOARD)

# # skip tinyusb
# BUILD_NO_TINYUSB = 1

# CFLAGS += -DTINYUF2_SELF_UPDATE

# SRC_C += \
# 	apps/self_update/self_update.c \
# 	$(TOP)/$(PORT_DIR)/apps/self_update/_build/bootloader_bin.c \
# 	$(TOP)/$(PORT_DIR)/boards.c \
# 	$(TOP)/$(PORT_DIR)/board_hmi.c \
# 	$(TOP)/$(PORT_DIR)/board_irq.c \

# INC += \
# 	$(TOP)/src \

# include ../app.mk

all:
	@echo "not implemented yet"
