# List of git submodules that is included as part of the UF2 version
GIT_SUBMODULES = tinyusb

include ../make.mk
include port.mk
include ../rules.mk

#------------------------------------------
# Self-update
#------------------------------------------
self-update:
	@echo "not implemented yet"
